services:
  ai:
    image: ai-backend:latest
    container_name: backend
    env_file: ".env"
    ports:
      - 3000:3000
      - 15000-15020:15000-15020
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE

  webhook:
    image: ai-backend:latest
    command: sh -c "npm run postcall"
    container_name: webhook
    env_file: ".env"
    ports:
      - 3001:3000
    restart: always
